# Generated by Django 4.2 on 2023-05-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, verbose_name='번호')),
                ('name', models.CharField(max_length=30, verbose_name='이름')),
                ('id', models.CharField(max_length=30, verbose_name='아이디')),
                ('phone', models.CharField(max_length=13, verbose_name='전화번호')),
                ('email', models.CharField(max_length=10, verbose_name='이메일')),
                ('pw', models.CharField(max_length=30, verbose_name='비밀번호')),
            ],
        ),
    ]
